#!/bin/bash
set -eu
NCPU=1
if [[ ${1-} =~ ^[0-9]+$ ]]; then
  NCPU="${1}"
elif [[ ${1-} == "all" ]] || [[ ${1-} == "max" ]]; then
  NCPU="$(nproc)"
fi
cd /src/php-8.2.0
printf "COMMAND: make -j%s &>/dev/null\n" "${NCPU}"
if ! make clean &>/dev/null; then
  printf -- "CLEANUP FAILED\n"
  exit 1
fi
if /usr/bin/time -o /dev/stdin --quiet -f 'RESULT: %E / %e (%S/%U)' make -j${NCPU} &>/dev/null; then
  printf -- "OK\n"
else
  printf -- "FAIL\n"
fi
